### ISSUE TITLE
Error in Run tests and install conda envs

### ISSUE THREAD

**Issue by xiaochen2015** [WatsonLab/MAGpy#43]
Hi, I tried to run the new version of MAGpy, and I got an error in running tests and install conda envs (forward step "conda env create -f envs/install.yaml" was corrected).

❯ snakemake -rp -s MAGpy --cores 1 --use-conda test
Building DAG of jobs...
Creating conda environment envs/checkm.yaml...
Downloading and installing remote packages.
CreateCondaEnvironmentException:
Could not create conda environment from /home/t640/user/xiaochen/software/MAGpy/envs/checkm.yaml:

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/t640/user/xiaochen/miniconda3/envs/magpy_install/lib/python3.10/site-packages/conda/exceptions.py", line 1080, in __call__
        return func(*args, **kwargs)
      File "/home/t640/user/xiaochen/miniconda3/envs/magpy_install/lib/python3.10/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/t640/user/xiaochen/miniconda3/envs/magpy_install/lib/python3.10/site-packages/conda_env/cli/main_create.py", line 141, in execute
        result[installer_type] = installer.install(prefix, pkg_specs, args, env)
      File "/home/t640/user/xiaochen/miniconda3/envs/magpy_install/lib/python3.10/site-packages/mamba/mamba_env.py", line 45, in mamba_install
        index = load_channels(pool, channel_urls, repos, prepend=False)
      File "/home/t640/user/xiaochen/miniconda3/envs/magpy_install/lib/python3.10/site-packages/mamba/utils.py", line 122, in load_channels
        index = get_index(
      File "/home/t640/user/xiaochen/miniconda3/envs/magpy_install/lib/python3.10/site-packages/mamba/utils.py", line 103, in get_index
        is_downloaded = dlist.download(True)
    RuntimeError: Multi-download failed.

`$ /home/t640/user/xiaochen/miniconda3/envs/magpy_install/bin/mamba create --quiet --file /home/t640/user/xiaochen/software/MAGpy/.snakemake/conda/80bd1d816c0e92c259e9c740d841735f.yaml --prefix /home/t640/user/xiaochen/software/MAGpy/.snakemake/conda/80bd1d816c0e92c259e9c740d841735f`

How can I solve this problem? Thank you!

**Comment by mw55309** [comment]
Sorry, please pull the latest repo and see f that solves things?
